version: '3'

services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin" #user = postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes:/var/lib/postgresql/data 
    networks:
      - fms-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - fms-network

  app:
    container_name: app
    build:
      context: ../src/
    networks:
      - fms-network
    ports:
      - "5001:80"
    depends_on: 
        - "db"
    environment:
      - DB_CONNECTION=Host=db;Port=5432;Database=FinancesManagementSystem;User ID=postgres;Password=admin
      - ASPNETCORE_ENVIRONMENT=Development

networks: 
  fms-network:
    driver: bridge
