version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin" #user = postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes:/var/lib/postgresql/data 
    networks:
      - fms-network

  app:
    container_name: app
    build:
      context: ../src
    entrypoint: dotnet Web.dll -launch-profile Docker
    networks:
      - fms-network
    ports:
      - "5001:5001"
    depends_on: 
        - "db"

networks: 
  fms-network:
    driver: bridge
