name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, test and analyze code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build
      run: dotnet build ./FinancesManagementSystem.sln --configuration Release

    - name: Test AutoMappers
      run: dotnet test --filter AutoMapper ./FinancesManagementSystem.sln --configuration Release

    - name: Test Services
      run: dotnet test --filter Service ./FinancesManagementSystem.sln --configuration Release

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
