name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build
      run: dotnet build ./src/FinancesManagementSystem.sln --configuration Release

    - name: Test AutoMappers
      run: dotnet test --filter AutoMapper ./src/FinancesManagementSystem.sln --configuration Release

    - name: Test Services
      run: dotnet test --filter Service ./src/FinancesManagementSystem.sln --configuration Release
